services:
  - type: web
    name: lsg-licencas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: SECRET_KEY
        value: troque_por_uma_chave_aleatoria_grande
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
